# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:

  install:
  conda_install_test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:2022.01
    resource_class: medium
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout 
      - run: sudo apt-get update && sudo apt-get install -y build-essential bash wget && sudo apt install gcc
      - run:
          command: |
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  # miniconda
            chmod +x Miniconda3-latest-Linux-x86_64.sh
            bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
            export PATH="$HOME/miniconda3/bin:$PATH"
            conda install conda-build
            conda create -n cig
            conda build conda-recipe -c conda-forge
            conda install -c local -c conda-forge cigarfilter -n cig -y
            source activate cig
            cigarfilter_test
workflows:
  install_and_test:
    jobs:
      - conda_install_test
