# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:

  install:
  conda_install_test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:2022.01
    resource_class: medium
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout 
      - run: sudo apt-get update && sudo apt-get install -y build-essential bash wget && sudo apt install gcc
      - run:
          command: |
            wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh  # miniforge
            chmod +x Miniforge3-Linux-x86_64.sh
            bash Miniforge3-Linux-x86_64.sh -b -p $HOME/Miniforge3
            export PATH="$HOME/Miniforge3/bin:$PATH"

            mamba create -n cf -c conda-forge cxx-compiler cmake make pip "conan<2" boa pkg-config
            mamba actvate cf
            conda mambabuild ./conda-recipe/ -c conda-forge
            mamba install -c local cigarfilter -n cf -y
            source activate cf
            cigarfilter_test
workflows:
  install_and_test:
    jobs:
      - conda_install_test
