# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:

  install:
  conda_install_test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:2022.01
    resource_class: medium
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout 
      - run: sudo apt update && sudo apt install -y bash wget build-essential
      - run:
          command: |
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  # miniconda
            chmod +x Miniconda3-latest-Linux-x86_64.sh
            bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
            export PATH="$HOME/miniconda3/bin:$PATH"
            conda config --add channels conda-forge
            conda install -c conda-forge mamba
            mamba create -n cf -c conda-forge cmake make pip "conan<2" boa pkg-config numpy
      - run:
          command: |
            export PATH="$HOME/miniconda3/bin:$PATH"
            source activate cf
            conda mambabuild ./conda-recipe/ -c conda-forge
            mamba install -c local -c conda-forge cigarfilter -n cf -y
            cigarfilter_test
workflows:
  install_and_test:
    jobs:
      - conda_install_test
